spring:
  cloud:
    services:
      registrationMethod: route

security:
  basic:
    enabled: false
    
zuul:
   prefix: /zuultest
   routes:
    multimime: 
      path: /cust/**
      serviceId: CUSTADDSERVICE    